language: node_js
dist: trusty
sudo: required
node_js: 6
script:
- bundle exec rake test
cache:
  directories:
  - node_modules
services:
- docker
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build -t repjarms/test-repo .
- docker run -d -p 127.0.0.1:80:4567 repjarms/test-repo /bin/sh -c "cd /root/test-repo; bundle exec foreman start;"
- docker ps -a
- docker run repjarms/test-repo /bin/sh -c "cd /root/test-repo; bundle exec rake test"
env:
  global:
  - secure: iGCNvYcJTompAPc2DW1JS491OE0oRi+mthUYGCShGi789LleIs7gH5kPRN84GKsJlbu+6Ai4xbbsnWoPaw8sOhN9ro1cph0SnB2ogNOBNKp67MVARTZkqrK6us6tei28UujADMXNCR34b3pFQT7QgsRcu55RsaahImRaPnDpX6hjAc5mrHw/cJM3tXyce6keQj1lEBoQVP3dn+yQ6PcpJyOLeZebo2t7xAFh+uFHfTS6ZT9eIcCu/op9XF6Awb4inWb3l+2iLIVJA9ezBaPZ7VPJ8ujus5b69PRDBobsNMcF+mn9uJn6ci70MViXX7Tv1i4TWm3jDCWY/d55f3yiRvJEZlHRvT4YZP4rVoZ1c+/vS85I0c4lxvWST0gLu2zzzTYkN+iW0j6lRAadPz5tDd4FCzwgmfoXuBc0FSQN9v7p+v2OzZtJZb1pUT8cjzeXwV84JH/4NK3UjHUZCOL6Mgyt1k8i3sSy1LRQAUWt9tjQv/b9tkWHfvFnMIqxG8n5IEWUUI1e454COoF4NC2lFKvIJonCm0CpN02z0umzhigwvFt198jHbvYncpTNjxeI+jGYF7QQeZxqlJLbtDIFZHkIz3eQJXXQ4qdP/iXojfmrWstD/+JMIYc3VQFG+AsPLyL1J8xUtZEcsXrBdIEpCkwid2fO+/01tkQkALp5F/0=
  - secure: TPSABK/GF4H2UIMLg8NzpGnZSQf2MIJyoW+vJnbhNJvbqAj8653ZMDA6L8AUd+1q3CcsZu7HmKHKSufyE8xEu7xwgWdWuPwMbkg6mah3Ptg8wsK9Dt1AXPEECffvby37s0t4UFLevvs7U/Qr6EGVgBnBuQwNq7KJrzNy74aYtd97CTvVrvUbFJBT9LQsMAsKG9Zc7bwbYuZGBzeCVOw9EDdzDCLLAcH786oQuayVtRCso7L6tR1vpXx4pXry1nF+LuFhYXBSKVEphh0q2f5/Gl//Gp3djLqGvI75aMg6NorO/EnvMiuXEp/gBxfKSdkgW0mFVSDxUyIcEDL0Mk4M/3zROs/vFHQSHluo6wkA8rnsko9Uiiqy3F3e9MoEiEKnmE3u0yfibCiParxdYYtGgvHRFkdUhcf6XjAFZF6YRF5pRc1kCmWRLBNc6B3Uls/OThiyyr1zoYQl1Z+tx9orVdH27YRlCD125fKz9GccsZBCH2eLS9K9G1yID2zR+rrMj/hViRGyR+zWz87TuHRPH+TdtTvbsl1JwB3AD0vLkjr6hb1PkkiCIllmcZoPBY7F8+Zhjy4bMddNNkLSh3+so9NzmfzE2bLOaYdjbk1mIvIQ1878cOkmdioUtNxwCKI3h+gbg4RLDlprz2xPcW5WnByxQzwaI9sspFE2IGhgqUM=
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  docker push repjarms/test-repo;
  fi
